# The name of your plugin as displayed in the Traefik Pilot web UI.
displayName: Header based whitelist middleware

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/icanbwell/cie.traefik-header-whitelist-plugin

# A brief description of what your plugin is doing.
summary: Whitelist requests based on header values

# Configuration data for your plugin.
# This is mandatory,
# and Traefik Pilot will try to execute the plugin with the configuration you provide as part of its startup validity tests.
testData:
  Rules:
  - Key: foo
    Value: bar